classDiagram
  %% ==== Core Classes ====
  class GameController {
    -List~IPlayer~ _players
    -IPlayer _currentPlayerIndex
    -IBoard board
    +StartGame()
    +TakeTurn(Coordinate)
    +SwitchTurn()
    +EndGame(): bool
    +CheckWinner(): IPlayer?
    +OnShotFired: Action<IPlayer, Coordinate, bool>
    +Shoot(Coordinate): bool
    +RemainingShips(): int
    +PlaceShip(ShipType, List~Coordinate~ ): bool
    +ReceiveShot(Coordinate): bool
    +AllShipsSunk(): bool
    +RegisterHit(Coordinate)
    +IsSunk(): bool
    +MarkHit(Coordinate)
    +HasShip(Coordinate):bool
  }

  class Ship {
    -string _name
    -int _size
    -int _hits
    -List~Coordinate~ _coordinates
  }

  class Coordinate {
    -int _x
    -int _y
    +Equals(Coordinate): bool
    +ToString(): string
  }

  %% ==== Interfaces ====
  class IPlayer {
    <<interface>>
    +GetName()
    +SetName()
  }

  class IBoard {
    <<interface>>
    +GetBoard(Coordinate): IBoard
  }

  %% ==== Implementations ====
  class Player {
    -string _name
    -IBoard _ownBoard
    -IBoard _trackingBoard
    -List~Ship~ _fleet
    +GetName()
    +SetName()
  }

  class Board {
    -IBoard[][] _grid
    -Coordinate _position
    -bool _isHit
    -Ship? _ship
    +GetBoard(Coordinate): IBoard

  }

  class ShipType {
    CARRIER
    BATTLESHIP
    CRUISER
    SUBMARINE
    DESTROYER
    <<enumeration>>
  }

  %% ==== Relationships ====
  GameController --> IPlayer
  GameController --> IBoard
  GameController --> Ship
  GameController --> Coordinate
  IPlayer <|.. Player
  IBoard <|.. Board
  Player --> Ship
  Board --> Coordinate
  Ship --> Coordinate
  Ship --> ShipType
  Player --> IBoard
  Board --> Ship
